### ISSUE TITLE
feature: uac options

### ISSUE THREAD

**Issue by 0xDylan** [13waves/waveOS#1]
hi!! i really like your work and I think that it is great!
one thing that I really did like about atlas is that it has that UAC thingy where it doesn't black out your screen

maybe you could add an option to the installer for other people who like the independent UAC just like me 

otherwise I love this version a lot more than the original

**Comment by 13waves** [comment]
Hi, this has been resolved in the latest commit/release, I replaced the "Remove Snipping Tool App" option with the "Disable Secure Desktop" option, Secure Desktop being the thing which blacks out your screen
